version: "2.3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    #runtime: nvidia # Expose NVIDIA GPUs
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=0 # The UID to run emby as (default: 2)
      - GID=0 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /docker/embyserver/config:/config # Configuration directory
      - /mnt/sda2/Videos:/mnt # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: unless-stopped
