[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
MergeTrackersEnabled=true
Session\AddTorrentStopped=false
Session\AddTrackersEnabled=true
Session\AddTrackersFromURLEnabled=true
Session\AdditionalTrackers=
Session\AdditionalTrackersURL=https://bitbucket.org/xiu2/trackerslistcollection/raw/master/all.txt
Session\AlternativeGlobalDLSpeedLimit=0
Session\AnnounceToAllTrackers=true
Session\DefaultSavePath=/downloads/Videos/Girls/中转站
Session\ExcludedFileNames=
Session\GlobalUPSpeedLimit=100
Session\MaxActiveDownloads=50
Session\MaxActiveTorrents=50
Session\Port=10090
Session\Preallocation=false
Session\QueueingSystemEnabled=true
Session\SSL\Port=3497
Session\ShareLimitAction=Stop
Session\SubcategoriesEnabled=true
Session\TempPath=/downloads/Videos/Girls/temp
Session\TempPathEnabled=true
Session\UseCategoryPathsInManualMode=true

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies="_octo=GH1.1.1280745287.1760261645; secure; SameSite=Lax; expires=Mon, 12-Oct-2026 09:34:05 GMT; domain=.github.com; path=/", "logged_in=no; secure; HttpOnly; SameSite=Lax; expires=Mon, 12-Oct-2026 09:34:05 GMT; domain=.github.com; path=/"
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=zh_CN
General\StatusbarExternalIPDisplayed=false
MailNotification\req_auth=true
WebUI\Address=*
WebUI\AuthSubnetWhitelist=192.168.2.0/24
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(ktrJ/3EIkUvNRx7jQhTRlQ==:RBfIRoBY1jaBzewARCdmxCwQ9GUoBMJOASwNODTLBYe/3+an8OwG1BB/K6F1TmWQoJc+OdHDwlPnlGJbOOIliw==)"
WebUI\Port=10089
WebUI\ServerDomains=*
WebUI\UseUPnP=false

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
Session\EnableProcessing=true

[SearchEngines]
disabledEngines=jackett
